#!/usr/bin/env python3
"""Build browser-readable note data for the static notes website."""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "notes-data.js"
ALLOWED_EXTENSIONS = {".md", ".txt", ".sql", ".scala"}
ALLOWED_TOP_LEVEL = {
    "FINAL_INTERVIEW_QUESTIONS_AND_ANSWERS.md",
    "FINAL_INTERVIEW_QUESTIONS_AND_ANSWERS_FILTERED.md",
}
SKIP_PARTS = {
    ".git",
    ".idea",
    ".venv",
    "target",
    "project",
    "conversationExport",
    "Images_From_Conversations",
}
MAX_BYTES = 2_500_000


def is_probably_text(path: Path) -> bool:
    try:
        sample = path.read_bytes()[:4096]
    except OSError:
        return False
    if b"\0" in sample:
        return False
    return True


def should_include(path: Path) -> bool:
    rel = path.relative_to(ROOT)
    if any(part in SKIP_PARTS for part in rel.parts):
        return False
    if path.stat().st_size > MAX_BYTES:
        return False
    if rel.parts[0] == "src" and "main" in rel.parts:
        return path.suffix.lower() in ALLOWED_EXTENSIONS or (not path.suffix and is_probably_text(path))
    if rel.parts[0] == "dsa":
        return path.suffix.lower() in {".md", ".txt", ".sql", ".scala"} or (not path.suffix and is_probably_text(path))
    return rel.name in ALLOWED_TOP_LEVEL


def title_from_path(path: Path) -> str:
    stem = path.stem if path.suffix else path.name
    title = re.sub(r"[_-]+", " ", stem).strip()
    title = re.sub(r"\s+", " ", title)
    return title.title() if title.isupper() or title.islower() else title


def category_from_path(path: Path) -> str:
    rel = path.relative_to(ROOT)
    if rel.parts[0] == "src" and len(rel.parts) > 2:
        return rel.parts[2].replace("_", " ")
    if rel.parts[0] == "dsa":
        return "DSA"
    return "Featured"


def summarize(text: str) -> str:
    cleaned = re.sub(r"```.*?```", " ", text, flags=re.S)
    cleaned = re.sub(r"^[#>\-*`\s]+", "", cleaned, flags=re.M)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned[:220] + ("..." if len(cleaned) > 220 else "")


def note_type(path: Path) -> str:
    if path.suffix:
        return path.suffix.lower().lstrip(".")
    return "txt"


def read_text(path: Path) -> str:
    for encoding in ("utf-8", "utf-8-sig", "latin-1"):
        try:
            return path.read_text(encoding=encoding)
        except UnicodeDecodeError:
            continue
    return path.read_text(encoding="utf-8", errors="replace")


def build_notes() -> list[dict[str, object]]:
    files = [path for path in ROOT.rglob("*") if path.is_file() and should_include(path)]
    notes = []
    for path in sorted(files, key=lambda item: str(item.relative_to(ROOT)).lower()):
        rel = path.relative_to(ROOT).as_posix()
        content = read_text(path).strip()
        if not content:
            continue
        digest = hashlib.sha1(rel.encode("utf-8")).hexdigest()[:12]
        words = len(re.findall(r"\b[\w'+-]+\b", content))
        notes.append(
            {
                "id": digest,
                "title": title_from_path(path),
                "path": rel,
                "category": category_from_path(path),
                "type": note_type(path),
                "summary": summarize(content),
                "words": words,
                "content": content,
            }
        )
    return notes


def main() -> None:
    notes = build_notes()
    payload = json.dumps(notes, ensure_ascii=False, separators=(",", ":"))
    OUTPUT.write_text(
        "// Generated by tools/build_notes_data.py. Do not edit by hand.\n"
        f"window.NOTES_DATA = {payload};\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUTPUT.relative_to(ROOT)} with {len(notes)} notes")


if __name__ == "__main__":
    main()
